### ISSUE TITLE
how to close popup when I get success code.

### ISSUE THREAD

**Issue by sunil1167** [XD2Sketch/react-oauth-popup#34] opened 2021-01-17 13:59 UTC

**Comment by kapekost** [comment] 2021-01-26 09:59
Hi, 
You need to finish the redirect sequence with a url param named 'code'. In most providers that's like a convention in the flow. 

if your flow doesn't have a '?code=x' param, you can mock one, you might find it useful example too, to pass data back to your client

**Comment by kgoedecke** [comment] 2021-01-27 10:19
@kapekost thanks a lot for helping here!

@sunil1167 Can you tell us which oAuth provider you're using?

**Comment by ganesh-papola** [comment] 2021-02-06 10:25
How to close popup manually after getting code?

**Comment by Parsa-FitForce** [comment] 2021-02-24 17:22
We are also having an issue with the popup not closing. We have '?code=x' param in the redirect URL, but the popup does not close on its own. 

![Screen Shot 2021-02-24 at 9 15 57 AM](https://user-images.githubusercontent.com/26828889/109039321-81794800-7681-11eb-8337-c195bdd914b4.png)

**Comment by sunilinzack** [comment] 2021-03-27 07:06
The issue is fixed. please redirect your response to the origin which you request window.open.

Ex:
    Your Website : http://localhost:3000/ - frontend
     Requested URL: http://localhost:4000/  - backend (new window)
     Response URL: http://localhost:3000/code=jkjsdjksdjksdjskdkj (new window)
     
Then Popup will close automatically. its security feature. we cannot access other origin parameters and data.

**Comment by ngeorge-peillex** [comment] 2021-03-31 15:33
I have the same issue. The popup is not closing when the code has been catched...
The redirect uri is the same than where I call the popup

**Comment by dsims** [comment] 2021-06-30 15:35
@sunilinzack What triggers the popup to close automatically?
I think the line here https://github.com/XD2Sketch/react-oauth-popup/blob/master/src/index.tsx#L74 only happens when the component unmounts, correct? So it would not happen when the popup redirects.

**Comment by kgoedecke** [comment] 2021-07-23 14:15
This should be fixed with release 1.0.5 https://github.com/XD2Sketch/react-oauth-popup/releases/tag/v1.0.5

Can you guys check if it works?

**Comment by David-Cohen35** [comment] 2021-07-26 14:57
it does not seem to be fixed with the release of 1.0.5

**Comment by kgoedecke** [comment] 2021-08-19 14:09
@sunil1167 @dsims @sunilinzack ping :)

**Comment by jeffreysnell** [comment] 2021-10-29 14:30
kgoedecke I've confirmed that this is fixed. For anyone who found this a bit unclear as I did. 

Un-mounting the OauthPopup in the success handler will call the onClose method and remove the popup.

Example:

```
const MyOathComp = () => {
    const [hasCode, setHasCode] = useState(false);

    function onCode() {
        window.opener.postMessage({ type: SUCCESS_TYPE, url: location.href }, "*");
    }

    function onClose(args) {
        console.log("window closed");
    }

    useEffect(() => {
        window.addEventListener("message", function (event) {
            if (get(event, "data.type") == SUCCESS_TYPE) {
                setHasCode(true);
            }
        });
    });

    return hasCode ? (
        <AfterLoginComponent />
    ) : (
        <OauthPopup url={OAUTH_URL} onCode={onCode} onClose={onClose}>
            <Button>Partner Login</Button>
        </OauthPopup>
    );
};


```

**Comment by kgoedecke** [comment] 2022-03-08 01:15
@jeffreysnell thanks for following up on this. Closing this for now.

**Closed by kgoedecke** 2022-03-08 01:15 UTC
